### ISSUE TITLE
Sending cells to REPL

### ISSUE THREAD

**Issue by Willywang8216** [axvr/zepl.vim#10]
Dear developer,

This is the my first post :)  and this is not an issue but rather a feature request :)

I'd like to suggest a feature of sending a code chunk delimited by some user defined strings. And after that, one can choose to stay at the present code chunk or move to the start of the next code chunk.

I have an ugly hack for this but it has problems with the first and the last chunk. I put `map <c-q>  /#--<CR>NV/#--<CR>kgz/#--<CR>` in my init.vim. It basically just search the previous occurence of the string and jump there -> enter visual line mode -> select the code to the next occurence of the string -> send it to REPL -> jump to the next occurence of the string...

It would be great if these feature is supported. 👍 

Thank you for this amazing plugin.

Example:

```python
#--
# code 1
some code

#--
#code 2 
some other code
```

**Comment by axvr** [comment]
Hi @Willywang8216, sorry that it has taken me so long to reply, I've been rather busy lately.  I'll look into adding this, but it might take a little while.

**Comment by Willywang8216** [comment]
No worries. Thanks for responding 🙂 and your efforts.  It's still a nice plugin.

**Comment by axvr** [comment]
@Willywang8216, I've pushed a new contrib module that adds this feature.

Enable it with:

```vim
runtime zepl/contrib/blocks.vim
```

Then set the patterns for block delimiters:

```vim
let g:repl_config = {
            \   'javascript': {
            \     'cmd': 'node',
            \     'block_delims': ['\m^\s*#\s*-\+\s*$', '\m^\s*#\s*-\+\s*$']
            \   }
            \ }
```

To send the block under the cursor to the REPL, just use the `:ReplSendBlock` command or the `gz<CR>` key binding.  (The `<CR>` is the enter/return key on your keyboard.)

Optionally you can also set some default block delimiters like so:

```vim
let g:zepl_block_delims = ['\m^\s*#\s*-\+\s*$', '\m^\s*#\s*-\+\s*$']
```

(Note: the patterns in the examples above should work for the example you gave above.)

See `:help zepl-blocks` for more info, and please let me know if you encounter any issues or are unsure of anything.

**Comment by Willywang8216** [comment]
Thank you so much for your work. but the pattern doesn't seem to work. It always says "No block found under cursor". Even if I change the block_delims to `'block_delims': ['#--', '#--']`, still not working... Is there a way to see what pattern my computer uses for block delimiter?? 

I tried also `'block_delims': ['#start', '#start']` with the cursor in indicated location. Not working either... :(

#start (cursor here)
code (or cursor here)
#start

**Comment by axvr** [comment]
Ah, sorry about that.  I've pushed a new version which should now work.

Also here are some improved delimiter patterns:
```vim
['^\s*#\s*-\+\s*\zs$', '^\ze\s*#\s*-\+\s*$']
```
